forest_palette:
	.word $0000, $0404, $0347, $0111, $0111, $0111, $0222, $0222, $0222, $0333, $0333, $0333, $0444, $0444, $0444, $0555

forest:
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
forest_00_00:
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $0f
	.byte $00, $00, $00, $9f
	.byte $00, $00, $7c, $db
	.byte $00, $00, $07, $fd
	.byte $6a, $66, $9b, $7c
forest_00_01:
	.byte $0d, $00, $00, $00
	.byte $fd, $00, $00, $00
	.byte $ff, $d0, $00, $00
	.byte $ff, $d5, $00, $00
	.byte $bc, $f9, $00, $00
	.byte $c7, $bc, $b7, $00
	.byte $dc, $d7, $b4, $00
	.byte $bd, $79, $3b, $70
forest_00_02:
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $0f, $00
	.byte $00, $00, $ff, $f0
	.byte $00, $0f, $ff, $f7
forest_00_03:
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $0c
forest_00_04:
	.byte $00, $00, $07, $00
	.byte $00, $00, $0f, $00
	.byte $00, $00, $9f, $d0
	.byte $00, $0c, $fd, $f9
	.byte $00, $b4, $bb, $c7
	.byte $09, $fd, $c4, $7b
	.byte $9b, $9d, $cc, $bb
	.byte $db, $99, $c9, $b5
forest_00_05:
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $c0
	.byte $50, $00, $00, $f7
	.byte $77, $00, $00, $ff
	.byte $75, $00, $0f, $ff
forest_00_06:
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $f9, $a0, $66, $ad
forest_00_07:
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $00, $00, $00
	.byte $00, $c0, $00, $00
	.byte $0f, $d0, $00, $00
	.byte $ff, $dc, $00, $40
	.byte $bf, $d7, $67, $b6
forest_01_00:
	.byte $66, $8b, $dd, $97
	.byte $6a, $68, $bd, $cb
	.byte $86, $87, $77, $cb
	.byte $76, $69, $75, $49
	.byte $ca, $64, $5b, $b3
	.byte $cb, $93, $57, $55
	.byte $94, $53, $42, $47
	.byte $77, $bb, $52, $22
forest_01_01:
	.byte $49, $55, $cc, $74
	.byte $77, $b7, $77, $45
	.byte $cb, $c5, $42, $75
	.byte $5b, $75, $34, $44
	.byte $23, $24, $45, $44
	.byte $74, $77, $5b, $44
	.byte $5b, $57, $34, $99
	.byte $77, $35, $29, $d4
forest_01_02:
	.byte $00, $0b, $7d, $d9
	.byte $0b, $fc, $d7, $9c
	.byte $8b, $9d, $bd, $c5
	.byte $dc, $9b, $9d, $97
	.byte $df, $b7, $47, $57
	.byte $9c, $f9, $b7, $b7
	.byte $77, $7d, $cb, $b5
	.byte $99, $4b, $47, $53
forest_01_03:
	.byte $00, $00, $00, $07
	.byte $b5, $00, $00, $5b
	.byte $b4, $00, $05, $f9
	.byte $3b, $70, $07, $f9
	.byte $cb, $77, $0f, $ff
	.byte $7b, $27, $fd, $fd
	.byte $57, $dd, $bb, $bf
	.byte $23, $dd, $dd, $94
forest_01_04:
	.byte $dd, $b4, $45, $57
	.byte $4c, $bb, $7b, $57
	.byte $47, $9c, $bc, $57
	.byte $c5, $54, $75, $43
	.byte $77, $43, $33, $34
	.byte $b4, $7b, $b7, $4b
	.byte $52, $57, $54, $55
	.byte $97, $22, $25, $32
forest_01_05:
	.byte $7b, $67, $ff, $ff
	.byte $c7, $40, $bf, $dd
	.byte $44, $4b, $bb, $b7
	.byte $3b, $7f, $ff, $db
	.byte $52, $bd, $bf, $dd
	.byte $3b, $bb, $bd, $dc
	.byte $bd, $fb, $c9, $b7
	.byte $5d, $fd, $b9, $99
forest_01_06:
	.byte $df, $5a, $66, $cd
	.byte $f4, $86, $64, $b9
	.byte $d7, $d4, $9c, $79
	.byte $bb, $bc, $9c, $b9
	.byte $bd, $79, $47, $c9
	.byte $b9, $74, $bb, $7b
	.byte $97, $9c, $c7, $75
	.byte $b7, $77, $77, $44
forest_01_07:
	.byte $c7, $4c, $9d, $f8
	.byte $dc, $cb, $7f, $fd
	.byte $9d, $79, $ff, $ff
	.byte $47, $59, $bb, $cd
	.byte $c9, $df, $dd, $49
	.byte $7b, $9b, $dd, $db
	.byte $44, $b9, $dd, $bb
	.byte $5d, $f9, $99, $79
forest_02_00:
	.byte $5b, $c4, $51, $22
	.byte $bb, $44, $42, $34
	.byte $72, $35, $71, $24
	.byte $44, $35, $23, $44
	.byte $45, $b3, $34, $a8
	.byte $57, $77, $72, $66
	.byte $54, $42, $4c, $a4
	.byte $72, $27, $fd, $98
forest_02_01:
	.byte $22, $22, $9f, $fc
	.byte $33, $34, $b9, $99
	.byte $42, $4b, $cc, $9b
	.byte $41, $97, $9c, $97
	.byte $a6, $dc, $74, $55
	.byte $88, $49, $bb, $bb
	.byte $79, $54, $b7, $77
	.byte $a4, $77, $43, $33
forest_02_02:
	.byte $4c, $53, $32, $34
	.byte $73, $75, $b5, $5b
	.byte $b4, $55, $77, $59
	.byte $47, $24, $24, $44
	.byte $bb, $52, $22, $7d
	.byte $74, $45, $f4, $79
	.byte $24, $55, $f4, $47
	.byte $54, $5d, $fd, $45
forest_02_03:
	.byte $9b, $bb, $fd, $cc
	.byte $dd, $bb, $9f, $99
	.byte $df, $d9, $4b, $75
	.byte $9b, $d9, $97, $95
	.byte $4c, $9d, $cb, $c7
	.byte $97, $7d, $7b, $d4
	.byte $9c, $44, $44, $75
	.byte $55, $54, $33, $33
forest_02_04:
	.byte $b7, $b2, $22, $32
	.byte $55, $44, $33, $39
	.byte $77, $b7, $44, $2f
	.byte $7c, $b5, $46, $bf
	.byte $b7, $74, $4f, $ff
	.byte $b2, $32, $6b, $bb
	.byte $23, $7c, $fd, $db
	.byte $55, $54, $fd, $fd
forest_02_05:
	.byte $f9, $c9, $db, $d9
	.byte $d7, $4c, $9d, $cb
	.byte $f9, $49, $4c, $5b
	.byte $ff, $cb, $53, $33
	.byte $fd, $d7, $54, $33
	.byte $df, $73, $55, $77
	.byte $7b, $bc, $45, $77
	.byte $bd, $c7, $c4, $54
forest_02_06:
	.byte $db, $bb, $54, $54
	.byte $bc, $57, $24, $54
	.byte $47, $42, $43, $35
	.byte $22, $47, $45, $43
	.byte $44, $35, $b4, $24
	.byte $74, $77, $74, $9f
	.byte $4b, $23, $1b, $ff
	.byte $35, $b2, $2b, $7f
forest_02_07:
	.byte $7d, $dd, $94, $47
	.byte $77, $7b, $cc, $bc
	.byte $b7, $44, $c7, $b5
	.byte $47, $c7, $43, $42
	.byte $47, $47, $55, $43
	.byte $c2, $54, $57, $b7
	.byte $fb, $23, $5b, $55
	.byte $c7, $32, $22, $22
forest_03_00:
	.byte $23, $47, $b9, $79
	.byte $34, $7b, $cb, $b5
	.byte $37, $c7, $77, $57
	.byte $13, $cb, $75, $7b
	.byte $a7, $4b, $bb, $b4
	.byte $97, $55, $54, $34
	.byte $c3, $55, $55, $57
	.byte $dc, $42, $55, $7b
forest_03_01:
	.byte $63, $44, $57, $75
	.byte $74, $32, $55, $37
	.byte $cb, $47, $22, $22
	.byte $54, $fc, $43, $44
	.byte $3d, $dd, $51, $4d
	.byte $c9, $97, $c6, $89
	.byte $cd, $bb, $bb, $67
	.byte $79, $c9, $55, $79
forest_03_02:
	.byte $57, $bf, $df, $73
	.byte $2b, $9b, $7b, $b4
	.byte $7d, $dd, $b9, $bc
	.byte $9b, $bd, $cb, $95
	.byte $d9, $b7, $97, $5b
	.byte $fc, $97, $47, $5b
	.byte $7b, $9c, $bb, $dd
	.byte $47, $bc, $b9, $db
forest_03_03:
	.byte $43, $77, $77, $75
	.byte $23, $57, $b7, $45
	.byte $49, $b2, $53, $b3
	.byte $5d, $f3, $22, $22
	.byte $ff, $fc, $22, $33
	.byte $df, $fb, $43, $44
	.byte $bb, $99, $91, $44
	.byte $f9, $cc, $b5, $64
forest_03_04:
	.byte $75, $9b, $9d, $dd
	.byte $bd, $dd, $bb, $bc
	.byte $3d, $ff, $b9, $47
	.byte $4b, $fb, $d9, $b9
	.byte $79, $7b, $bc, $f9
	.byte $c9, $4b, $7f, $9b
	.byte $49, $97, $77, $47
	.byte $95, $cc, $42, $32
forest_03_05:
	.byte $bc, $9b, $43, $22
	.byte $b7, $74, $7b, $42
	.byte $94, $7b, $c7, $b4
	.byte $b9, $77, $b7, $42
	.byte $fb, $bb, $54, $73
	.byte $bb, $35, $27, $4a
	.byte $37, $32, $53, $74
	.byte $24, $37, $45, $22
forest_03_06:
	.byte $13, $33, $dd, $d9
	.byte $32, $34, $b9, $cd
	.byte $73, $9d, $99, $9f
	.byte $34, $9d, $cc, $47
	.byte $14, $47, $bb, $c7
	.byte $66, $c4, $74, $cb
	.byte $87, $d7, $93, $45
	.byte $ad, $fd, $4b, $43
forest_03_07:
	.byte $9c, $b4, $33, $23
	.byte $c9, $75, $34, $24
	.byte $97, $47, $b2, $34
	.byte $55, $bc, $54, $14
	.byte $bb, $b7, $47, $8a
	.byte $b7, $43, $55, $66
	.byte $44, $34, $43, $66
	.byte $43, $75, $33, $7c
forest_04_00:
	.byte $79, $43, $22, $9f
	.byte $77, $94, $43, $b5
	.byte $99, $55, $19, $d4
	.byte $54, $7b, $9c, $fd
	.byte $77, $9b, $3f, $fd
	.byte $bb, $73, $db, $ff
	.byte $57, $37, $db, $97
	.byte $44, $5f, $cf, $bd
forest_04_01:
	.byte $b4, $55, $7c, $75
	.byte $bc, $bb, $b5, $34
	.byte $5b, $7b, $33, $73
	.byte $52, $34, $45, $42
	.byte $97, $75, $57, $43
	.byte $77, $45, $42, $31
	.byte $cb, $34, $23, $34
	.byte $c7, $72, $34, $18
forest_04_02:
	.byte $cb, $43, $bd, $4c
	.byte $75, $55, $dd, $b9
	.byte $34, $77, $bc, $d9
	.byte $32, $4b, $77, $bc
	.byte $33, $47, $77, $4c
	.byte $14, $37, $bc, $42
	.byte $12, $44, $55, $55
	.byte $41, $33, $f3, $55
forest_04_03:
	.byte $bd, $b9, $54, $46
	.byte $7c, $47, $4b, $74
	.byte $47, $55, $cc, $75
	.byte $cb, $c7, $75, $44
	.byte $7b, $c2, $43, $b1
	.byte $33, $44, $34, $34
	.byte $44, $44, $74, $34
	.byte $b7, $75, $75, $38
forest_04_04:
	.byte $1b, $44, $55, $77
	.byte $53, $52, $b3, $77
	.byte $14, $23, $f7, $73
	.byte $32, $27, $fc, $22
	.byte $12, $5f, $ff, $f2
	.byte $41, $bf, $fd, $b7
	.byte $44, $db, $b7, $bc
	.byte $6b, $dd, $bc, $d7
forest_04_05:
	.byte $47, $3b, $72, $47
	.byte $75, $77, $75, $54
	.byte $73, $41, $32, $9d
	.byte $37, $22, $33, $7d
	.byte $22, $34, $24, $74
	.byte $23, $35, $54, $5b
	.byte $54, $51, $24, $55
	.byte $b1, $21, $43, $42
forest_04_06:
	.byte $8b, $99, $75, $7b
	.byte $bd, $cb, $74, $37
	.byte $74, $95, $5b, $52
	.byte $b5, $55, $bb, $42
	.byte $7c, $c7, $44, $42
	.byte $54, $44, $34, $11
	.byte $55, $55, $74, $48
	.byte $5b, $d4, $44, $56
forest_04_07:
	.byte $77, $55, $43, $55
	.byte $37, $23, $37, $bb
	.byte $22, $33, $35, $59
	.byte $43, $34, $b9, $53
	.byte $44, $53, $79, $97
	.byte $41, $25, $45, $7c
	.byte $8a, $83, $57, $44
	.byte $66, $45, $75, $75
forest_05_00:
	.byte $97, $99, $bc, $fb
	.byte $3b, $db, $b4, $b7
	.byte $24, $fc, $b7, $77
	.byte $47, $b9, $bd, $bc
	.byte $5c, $45, $4d, $77
	.byte $74, $7b, $53, $32
	.byte $84, $75, $54, $74
	.byte $44, $33, $57, $bb
forest_05_01:
	.byte $95, $bb, $41, $88
	.byte $57, $cb, $76, $86
	.byte $7b, $77, $36, $6a
	.byte $c5, $43, $b6, $68
	.byte $b4, $24, $33, $66
	.byte $24, $55, $33, $8b
	.byte $55, $7b, $43, $8d
	.byte $55, $53, $34, $8d
forest_05_02:
	.byte $aa, $4c, $fc, $2b
	.byte $66, $ff, $fd, $92
	.byte $68, $f7, $df, $53
	.byte $dd, $bc, $79, $bb
	.byte $9d, $dd, $bd, $9b
	.byte $b9, $bc, $c9, $54
	.byte $db, $77, $74, $7c
	.byte $bd, $99, $b7, $b7
forest_05_03:
	.byte $b5, $53, $34, $28
	.byte $22, $42, $24, $18
	.byte $23, $22, $32, $1a
	.byte $23, $43, $34, $b6
	.byte $51, $14, $1d, $f9
	.byte $78, $a6, $4f, $fd
	.byte $bb, $6b, $ff, $ff
	.byte $b3, $a8, $bb, $cd
forest_05_04:
	.byte $8b, $9d, $db, $97
	.byte $db, $97, $b9, $47
	.byte $dd, $b9, $47, $77
	.byte $b9, $cb, $cb, $c7
	.byte $57, $3c, $5b, $b4
	.byte $59, $54, $34, $24
	.byte $b7, $55, $53, $55
	.byte $73, $55, $7b, $57
forest_05_05:
	.byte $4b, $16, $61, $22
	.byte $cb, $b5, $81, $15
	.byte $7b, $35, $68, $19
	.byte $53, $75, $68, $df
	.byte $34, $35, $a6, $db
	.byte $45, $42, $bd, $4b
	.byte $7b, $44, $dd, $b9
	.byte $44, $44, $bd, $d9
forest_05_06:
	.byte $2d, $f3, $23, $56
	.byte $ff, $fd, $41, $76
	.byte $df, $fc, $15, $68
	.byte $bb, $99, $ca, $6c
	.byte $d9, $cc, $b5, $8d
	.byte $bf, $b9, $54, $54
	.byte $7c, $47, $4b, $75
	.byte $55, $55, $bc, $77
forest_05_07:
	.byte $66, $dd, $33, $79
	.byte $69, $cd, $52, $23
	.byte $cc, $77, $b2, $33
	.byte $79, $cb, $57, $43
	.byte $b4, $55, $7b, $91
	.byte $bc, $77, $7b, $4a
	.byte $5b, $b7, $43, $48
	.byte $53, $34, $44, $3b
forest_06_00:
	.byte $b3, $42, $25, $57
	.byte $e5, $23, $32, $21
	.byte $b7, $53, $33, $32
	.byte $bb, $95, $34, $42
	.byte $c9, $59, $74, $11
	.byte $77, $bd, $55, $aa
	.byte $9c, $c7, $47, $88
	.byte $bc, $43, $54, $a5
forest_06_01:
	.byte $74, $22, $34, $94
	.byte $22, $45, $49, $b4
	.byte $33, $bf, $34, $5c
	.byte $45, $cc, $75, $44
	.byte $49, $d9, $77, $33
	.byte $c9, $47, $75, $72
	.byte $9b, $b7, $7b, $52
	.byte $55, $9b, $73, $44
forest_06_02:
	.byte $99, $db, $cb, $75
	.byte $45, $cb, $7b, $23
	.byte $b5, $23, $33, $55
	.byte $54, $b5, $75, $4b
	.byte $37, $5b, $57, $35
	.byte $34, $57, $47, $22
	.byte $7d, $22, $22, $37
	.byte $b9, $72, $33, $34
forest_06_03:
	.byte $34, $df, $dd, $49
	.byte $57, $9b, $dd, $db
	.byte $59, $b9, $dd, $bb
	.byte $bd, $f9, $99, $79
	.byte $7d, $dd, $94, $47
	.byte $77, $7b, $cc, $bc
	.byte $b7, $44, $c7, $b5
	.byte $47, $b7, $43, $42
forest_06_04:
	.byte $c9, $33, $7b, $55
	.byte $cb, $b2, $32, $23
	.byte $94, $55, $22, $32
	.byte $77, $bb, $72, $43
	.byte $5b, $c4, $51, $41
	.byte $bb, $44, $4a, $8a
	.byte $72, $35, $7a, $a6
	.byte $44, $35, $23, $86
forest_06_05:
	.byte $22, $5c, $77, $bc
	.byte $23, $47, $79, $4c
	.byte $24, $37, $bc, $42
	.byte $52, $17, $45, $55
	.byte $15, $9d, $23, $75
	.byte $a8, $b9, $52, $27
	.byte $87, $cb, $75, $22
	.byte $cb, $45, $7b, $43
forest_06_06:
	.byte $cb, $b7, $77, $44
	.byte $7b, $c3, $43, $73
	.byte $33, $44, $34, $42
	.byte $44, $44, $74, $29
	.byte $b7, $75, $b5, $7d
	.byte $b5, $53, $37, $cc
	.byte $22, $42, $4b, $c9
	.byte $22, $25, $c5, $77
forest_06_07:
	.byte $77, $75, $74, $3c
	.byte $24, $55, $24, $bc
	.byte $32, $22, $35, $74
	.byte $44, $34, $3b, $bb
	.byte $67, $41, $55, $79
	.byte $7a, $68, $b7, $75
	.byte $78, $a6, $7b, $c9
	.byte $55, $a6, $47, $4c
forest_07_00:
	.byte $43, $55, $43, $46
	.byte $75, $79, $74, $83
	.byte $99, $55, $23, $a8
	.byte $b4, $32, $31, $6a
	.byte $d7, $33, $41, $67
	.byte $77, $44, $18, $a5
	.byte $77, $76, $86, $99
	.byte $95, $79, $65, $bd
forest_07_01:
	.byte $77, $4c, $35, $47
	.byte $33, $cd, $b7, $bb
	.byte $29, $bd, $d4, $55
	.byte $95, $55, $7b, $55
	.byte $cc, $c7, $7b, $95
	.byte $59, $9c, $97, $73
	.byte $59, $5c, $77, $49
	.byte $95, $35, $57, $bc
forest_07_02:
	.byte $cb, $75, $43, $52
	.byte $45, $7b, $11, $17
	.byte $cb, $74, $66, $84
	.byte $44, $44, $36, $a6
	.byte $77, $55, $46, $67
	.byte $33, $22, $46, $47
	.byte $53, $43, $46, $a7
	.byte $91, $14, $a6, $be
forest_07_03:
	.byte $47, $97, $55, $43
	.byte $35, $dd, $c7, $b7
	.byte $3d, $ce, $c7, $55
	.byte $49, $59, $99, $32
	.byte $cd, $d7, $9b, $b5
	.byte $bc, $dd, $b7, $54
	.byte $5c, $9d, $b9, $9b
	.byte $99, $57, $b9, $bd
forest_07_04:
	.byte $45, $b3, $34, $aa
	.byte $57, $77, $52, $86
	.byte $54, $42, $26, $64
	.byte $72, $24, $34, $48
	.byte $23, $42, $14, $a6
	.byte $34, $44, $14, $66
	.byte $97, $11, $4a, $46
	.byte $51, $34, $68, $a6
forest_07_05:
	.byte $55, $cb, $74, $43
	.byte $55, $44, $44, $11
	.byte $34, $77, $55, $48
	.byte $22, $33, $22, $68
	.byte $13, $43, $43, $46
	.byte $a4, $11, $14, $68
	.byte $66, $68, $6a, $7b
	.byte $a6, $88, $a8, $9d
forest_07_06:
	.byte $33, $45, $7c, $57
	.byte $11, $45, $57, $bb
	.byte $66, $47, $73, $34
	.byte $66, $95, $3b, $75
	.byte $6d, $db, $22, $44
	.byte $cd, $dd, $53, $23
	.byte $77, $9c, $41, $44
	.byte $cb, $39, $98, $a8
forest_07_07:
	.byte $7b, $75, $55, $45
	.byte $74, $75, $57, $95
	.byte $35, $54, $33, $59
	.byte $74, $44, $33, $35
	.byte $32, $66, $13, $3d
	.byte $31, $66, $41, $57
	.byte $14, $6a, $a5, $9c
	.byte $88, $66, $6c, $75
forest_end:
