
forest_inner:
forest_inner_00_00:
	.byte $88, $a8, $76, $58
	.byte $a8, $45, $58, $45
	.byte $44, $64, $44, $68
	.byte $86, $84, $55, $6f
	.byte $45, $23, $73, $6e
	.byte $22, $43, $7c, $db
	.byte $44, $27, $75, $ed
	.byte $47, $77, $9b, $6c
forest_inner_00_01:
	.byte $bd, $a8, $b8, $aa
	.byte $fe, $ac, $b8, $53
	.byte $ff, $d8, $64, $34
	.byte $ff, $d5, $33, $86
	.byte $bd, $f9, $65, $88
	.byte $c6, $bc, $b6, $65
	.byte $dc, $d6, $b5, $23
	.byte $bd, $69, $3b, $84
forest_inner_00_02:
	.byte $55, $79, $97, $8d
	.byte $56, $97, $79, $54
	.byte $55, $99, $76, $a4
	.byte $52, $57, $95, $55
	.byte $34, $79, $75, $58
	.byte $84, $97, $7e, $35
	.byte $42, $97, $ee, $e4
	.byte $22, $be, $ee, $e6
forest_inner_00_03:
	.byte $cb, $db, $ec, $c5
	.byte $cb, $ec, $dc, $54
	.byte $88, $a8, $68, $44
	.byte $c5, $34, $45, $5b
	.byte $58, $8b, $aa, $88
	.byte $35, $88, $86, $82
	.byte $23, $33, $33, $33
	.byte $32, $42, $23, $3c
forest_inner_00_04:
	.byte $45, $67, $77, $7b
	.byte $56, $57, $7e, $79
	.byte $62, $29, $7e, $d7
	.byte $54, $4c, $ed, $e9
	.byte $65, $95, $bb, $c6
	.byte $36, $ed, $c5, $6b
	.byte $9b, $9d, $cc, $bb
	.byte $db, $99, $c9, $b6
forest_inner_00_05:
	.byte $77, $77, $77, $65
	.byte $79, $96, $bd, $68
	.byte $77, $96, $5d, $c6
	.byte $77, $66, $46, $a8
	.byte $99, $46, $54, $cc
	.byte $79, $56, $58, $f6
	.byte $88, $44, $66, $ff
	.byte $85, $44, $4e, $ee
forest_inner_00_06:
	.byte $cb, $ca, $8a, $77
	.byte $6b, $8a, $44, $67
	.byte $45, $58, $8b, $97
	.byte $b8, $a8, $cd, $86
	.byte $bc, $ca, $88, $45
	.byte $8a, $83, $45, $65
	.byte $32, $54, $44, $56
	.byte $f8, $58, $65, $2d
forest_inner_00_07:
	.byte $7b, $77, $5a, $b8
	.byte $b7, $77, $84, $6b
	.byte $79, $96, $4a, $63
	.byte $97, $79, $44, $6a
	.byte $77, $c6, $23, $24
	.byte $9e, $d7, $22, $43
	.byte $ee, $dc, $72, $23
	.byte $be, $d6, $77, $96
forest_inner_01_00:
	.byte $77, $9b, $dd, $96
	.byte $99, $77, $bd, $cb
	.byte $97, $76, $66, $cb
	.byte $69, $99, $65, $59
	.byte $c9, $75, $5b, $b3
	.byte $cb, $a4, $58, $66
	.byte $95, $64, $42, $48
	.byte $68, $bb, $52, $22
forest_inner_01_01:
	.byte $59, $55, $cc, $84
	.byte $66, $b8, $88, $45
	.byte $cb, $c6, $42, $85
	.byte $5b, $86, $34, $45
	.byte $23, $24, $46, $44
	.byte $84, $88, $6b, $44
	.byte $6b, $68, $34, $99
	.byte $88, $36, $29, $d5
forest_inner_01_02:
	.byte $22, $7b, $6d, $d9
	.byte $2b, $ec, $d6, $9c
	.byte $7b, $9d, $bd, $c5
	.byte $dc, $9b, $9d, $96
	.byte $de, $b6, $56, $58
	.byte $9c, $e9, $b6, $b8
	.byte $66, $6d, $cb, $b6
	.byte $99, $5b, $48, $63
forest_inner_01_03:
	.byte $24, $44, $44, $55
	.byte $b4, $42, $36, $2b
	.byte $b4, $42, $25, $e9
	.byte $3b, $89, $79, $e9
	.byte $cb, $88, $9e, $ee
	.byte $8b, $26, $ed, $ed
	.byte $66, $dd, $bb, $be
	.byte $23, $dd, $dd, $95
forest_inner_01_04:
	.byte $dd, $b5, $55, $58
	.byte $5c, $bb, $6b, $68
	.byte $56, $9c, $bc, $68
	.byte $c5, $54, $86, $43
	.byte $68, $43, $33, $34
	.byte $b4, $8b, $b8, $4b
	.byte $52, $68, $64, $66
	.byte $98, $22, $26, $32
forest_inner_01_05:
	.byte $8b, $24, $ee, $ee
	.byte $c8, $42, $be, $dd
	.byte $44, $46, $bb, $b6
	.byte $3b, $6e, $ee, $db
	.byte $62, $bd, $be, $dd
	.byte $3b, $bb, $bd, $dc
	.byte $bd, $eb, $c9, $b6
	.byte $5d, $ed, $b9, $99
forest_inner_01_06:
	.byte $de, $68, $a5, $cd
	.byte $e5, $52, $44, $b9
	.byte $d6, $d3, $9c, $69
	.byte $bb, $bc, $9c, $b9
	.byte $bd, $69, $46, $c9
	.byte $b9, $64, $bb, $6b
	.byte $96, $9c, $c8, $86
	.byte $b6, $88, $88, $44
forest_inner_01_07:
	.byte $c6, $5c, $ad, $e6
	.byte $dc, $cb, $8e, $ed
	.byte $9d, $6a, $ee, $ee
	.byte $56, $58, $bb, $cd
	.byte $ca, $de, $dd, $59
	.byte $8b, $9b, $dd, $db
	.byte $45, $b9, $dd, $bb
	.byte $5d, $e9, $99, $69
forest_inner_02_00:
	.byte $5b, $c4, $62, $22
	.byte $bb, $44, $42, $34
	.byte $82, $36, $82, $24
	.byte $44, $36, $23, $25
	.byte $46, $b3, $34, $77
	.byte $68, $88, $82, $97
	.byte $64, $42, $5c, $76
	.byte $82, $26, $ed, $97
forest_inner_02_01:
	.byte $22, $22, $9e, $ec
	.byte $33, $34, $b9, $99
	.byte $42, $4b, $cc, $9b
	.byte $22, $96, $9c, $98
	.byte $77, $dc, $65, $56
	.byte $77, $59, $bb, $bb
	.byte $69, $54, $b8, $88
	.byte $94, $88, $43, $33
forest_inner_02_02:
	.byte $5c, $53, $32, $34
	.byte $83, $86, $b6, $6b
	.byte $b4, $66, $88, $69
	.byte $48, $24, $24, $45
	.byte $bb, $62, $22, $6d
	.byte $84, $46, $e4, $69
	.byte $24, $65, $e4, $56
	.byte $64, $5d, $ed, $55
forest_inner_02_03:
	.byte $9b, $bb, $ed, $cc
	.byte $dd, $bb, $9e, $99
	.byte $de, $d9, $5b, $65
	.byte $9b, $d9, $96, $95
	.byte $5c, $9d, $cb, $c8
	.byte $96, $6d, $8b, $d4
	.byte $9c, $54, $44, $86
	.byte $55, $64, $33, $33
forest_inner_02_04:
	.byte $b8, $b2, $22, $32
	.byte $56, $44, $33, $39
	.byte $88, $b8, $24, $2e
	.byte $8c, $b6, $47, $be
	.byte $b8, $84, $7e, $ee
	.byte $b2, $32, $7b, $bb
	.byte $23, $6c, $ed, $db
	.byte $66, $65, $ed, $ed
forest_inner_02_05:
	.byte $e9, $c9, $db, $d9
	.byte $d6, $5c, $9d, $cb
	.byte $e9, $59, $5c, $5b
	.byte $ee, $cb, $53, $33
	.byte $ed, $d8, $64, $33
	.byte $de, $63, $66, $88
	.byte $6b, $bc, $46, $88
	.byte $bd, $c6, $c4, $64
forest_inner_02_06:
	.byte $db, $bb, $64, $64
	.byte $bc, $68, $24, $64
	.byte $48, $42, $43, $36
	.byte $22, $48, $46, $43
	.byte $44, $36, $b4, $25
	.byte $84, $88, $84, $9e
	.byte $4b, $23, $2b, $ee
	.byte $36, $b2, $2b, $6e
forest_inner_02_07:
	.byte $6d, $dd, $95, $56
	.byte $86, $6b, $cc, $bc
	.byte $b6, $55, $c8, $b6
	.byte $56, $c6, $43, $42
	.byte $58, $48, $66, $43
	.byte $c2, $64, $68, $b8
	.byte $eb, $23, $6b, $66
	.byte $c6, $32, $22, $22
forest_inner_03_00:
	.byte $23, $46, $b9, $6b
	.byte $34, $6b, $cb, $b5
	.byte $36, $c6, $66, $58
	.byte $24, $cb, $65, $8b
	.byte $96, $5b, $bb, $b4
	.byte $a8, $55, $64, $34
	.byte $c4, $56, $66, $66
	.byte $dc, $52, $66, $6b
forest_inner_03_01:
	.byte $93, $44, $68, $86
	.byte $85, $32, $66, $38
	.byte $cb, $56, $22, $22
	.byte $64, $ec, $43, $44
	.byte $3d, $dd, $52, $2d
	.byte $c9, $96, $c7, $79
	.byte $cd, $bb, $bb, $76
	.byte $69, $c9, $56, $89
forest_inner_03_02:
	.byte $68, $be, $de, $63
	.byte $2b, $9b, $6b, $b4
	.byte $6d, $dd, $b9, $bc
	.byte $9b, $bd, $cb, $95
	.byte $d9, $b6, $96, $5b
	.byte $ec, $96, $58, $6b
	.byte $6b, $9c, $bb, $dd
	.byte $56, $bc, $b9, $db
forest_inner_03_03:
	.byte $43, $88, $88, $86
	.byte $23, $58, $b8, $46
	.byte $49, $b2, $63, $b3
	.byte $5d, $e3, $22, $22
	.byte $ee, $ec, $22, $33
	.byte $de, $eb, $43, $45
	.byte $bb, $99, $92, $25
	.byte $e9, $cc, $b6, $75
forest_inner_03_04:
	.byte $86, $9b, $9d, $dd
	.byte $bd, $dd, $bb, $bc
	.byte $3d, $ee, $b9, $56
	.byte $4b, $eb, $d9, $b9
	.byte $69, $6b, $bc, $e9
	.byte $c9, $5b, $6e, $9b
	.byte $59, $96, $66, $48
	.byte $95, $cc, $52, $32
forest_inner_03_05:
	.byte $bc, $9b, $43, $22
	.byte $b6, $64, $8b, $42
	.byte $95, $8b, $c8, $b4
	.byte $b9, $88, $b8, $42
	.byte $eb, $bb, $64, $83
	.byte $bb, $36, $28, $49
	.byte $38, $32, $63, $84
	.byte $24, $38, $46, $22
forest_inner_03_06:
	.byte $23, $33, $dd, $d9
	.byte $32, $34, $b9, $cd
	.byte $83, $9d, $99, $9e
	.byte $34, $9d, $cc, $56
	.byte $22, $56, $bb, $c6
	.byte $79, $c5, $65, $cb
	.byte $77, $d6, $93, $46
	.byte $7d, $ed, $4b, $43
forest_inner_03_07:
	.byte $9c, $b5, $33, $23
	.byte $c9, $65, $34, $24
	.byte $98, $48, $b2, $34
	.byte $55, $bc, $62, $22
	.byte $bb, $b8, $46, $97
	.byte $b8, $43, $65, $77
	.byte $44, $34, $43, $76
	.byte $43, $86, $33, $6c
forest_inner_04_00:
	.byte $88, $53, $22, $9e
	.byte $68, $82, $43, $b5
	.byte $aa, $55, $29, $d4
	.byte $65, $8b, $8c, $ed
	.byte $88, $8b, $4e, $ed
	.byte $bb, $84, $db, $ee
	.byte $58, $46, $db, $96
	.byte $45, $6e, $ce, $bd
forest_inner_04_01:
	.byte $b5, $55, $8c, $86
	.byte $bc, $bb, $b6, $34
	.byte $5b, $8b, $33, $83
	.byte $52, $34, $46, $42
	.byte $98, $86, $68, $43
	.byte $68, $46, $42, $32
	.byte $cb, $34, $23, $32
	.byte $c6, $62, $34, $29
forest_inner_04_02:
	.byte $cb, $53, $bd, $5c
	.byte $86, $65, $dd, $b9
	.byte $34, $88, $bc, $d9
	.byte $32, $4b, $66, $bc
	.byte $33, $56, $66, $5c
	.byte $24, $36, $bc, $52
	.byte $22, $45, $55, $66
	.byte $72, $33, $e3, $66
forest_inner_04_03:
	.byte $bd, $b9, $54, $99
	.byte $6c, $58, $4b, $64
	.byte $56, $56, $cc, $86
	.byte $cb, $c8, $86, $42
	.byte $8b, $c2, $43, $b2
	.byte $33, $44, $34, $34
	.byte $44, $44, $84, $35
	.byte $b8, $86, $86, $35
forest_inner_04_04:
	.byte $2b, $44, $66, $88
	.byte $63, $62, $b3, $88
	.byte $24, $23, $e8, $83
	.byte $32, $26, $ec, $22
	.byte $22, $5e, $ee, $e2
	.byte $22, $be, $ed, $b6
	.byte $22, $db, $b6, $bc
	.byte $7b, $dd, $bc, $d6
forest_inner_04_05:
	.byte $48, $3b, $82, $46
	.byte $86, $88, $86, $64
	.byte $83, $42, $32, $9d
	.byte $38, $22, $33, $6d
	.byte $22, $34, $25, $65
	.byte $23, $36, $65, $5b
	.byte $54, $62, $22, $56
	.byte $b2, $22, $23, $42
forest_inner_04_06:
	.byte $9b, $99, $86, $8b
	.byte $bd, $cb, $84, $38
	.byte $65, $95, $6b, $62
	.byte $b5, $56, $bb, $42
	.byte $6c, $c8, $44, $42
	.byte $64, $44, $34, $22
	.byte $66, $66, $84, $49
	.byte $6b, $d4, $44, $57
forest_inner_04_07:
	.byte $88, $66, $44, $68
	.byte $38, $23, $38, $bb
	.byte $22, $33, $35, $5a
	.byte $43, $35, $ba, $64
	.byte $44, $63, $8a, $a8
	.byte $22, $26, $46, $8c
	.byte $77, $74, $68, $54
	.byte $79, $75, $85, $85
forest_inner_05_00:
	.byte $88, $99, $bc, $eb
	.byte $4b, $db, $b5, $b6
	.byte $25, $ec, $b6, $66
	.byte $46, $b9, $bd, $bc
	.byte $5c, $55, $5d, $88
	.byte $65, $6b, $53, $32
	.byte $95, $85, $64, $84
	.byte $74, $33, $68, $bb
forest_inner_05_01:
	.byte $95, $bb, $42, $67
	.byte $58, $cb, $87, $79
	.byte $8b, $88, $36, $79
	.byte $c6, $43, $b9, $99
	.byte $b4, $24, $33, $99
	.byte $24, $66, $33, $9b
	.byte $66, $8b, $43, $9d
	.byte $66, $63, $34, $9d
forest_inner_05_02:
	.byte $77, $7c, $ec, $2b
	.byte $77, $ee, $ed, $92
	.byte $97, $e6, $de, $53
	.byte $dd, $bc, $69, $bb
	.byte $9d, $dd, $bd, $9b
	.byte $b9, $bc, $c9, $54
	.byte $db, $66, $65, $8c
	.byte $bd, $99, $b8, $b8
forest_inner_05_03:
	.byte $b6, $63, $34, $27
	.byte $22, $42, $24, $26
	.byte $23, $22, $32, $27
	.byte $23, $43, $35, $b6
	.byte $62, $22, $2d, $e9
	.byte $87, $b7, $9e, $ed
	.byte $bb, $79, $ee, $ee
	.byte $b3, $b6, $bb, $cd
forest_inner_05_04:
	.byte $7b, $9d, $db, $96
	.byte $db, $96, $b9, $58
	.byte $dd, $b9, $56, $68
	.byte $b9, $cb, $cb, $c8
	.byte $56, $3c, $5b, $b4
	.byte $59, $54, $34, $24
	.byte $b8, $66, $63, $66
	.byte $63, $66, $8b, $68
forest_inner_05_05:
	.byte $4b, $27, $72, $22
	.byte $cb, $b6, $92, $25
	.byte $8b, $36, $79, $29
	.byte $63, $86, $79, $de
	.byte $34, $36, $79, $db
	.byte $46, $42, $bd, $5b
	.byte $8b, $44, $dd, $b9
	.byte $44, $45, $bd, $d9
forest_inner_05_06:
	.byte $2d, $e3, $23, $27
	.byte $ee, $ed, $42, $76
	.byte $de, $ec, $24, $77
	.byte $bb, $99, $c7, $6c
	.byte $d9, $cc, $b6, $6d
	.byte $be, $b9, $54, $65
	.byte $6c, $58, $4b, $85
	.byte $55, $56, $bc, $88
forest_inner_05_07:
	.byte $97, $dd, $44, $8a
	.byte $79, $cd, $52, $24
	.byte $cc, $66, $b2, $43
	.byte $69, $cb, $58, $54
	.byte $b5, $55, $8b, $a2
	.byte $bc, $88, $8b, $47
	.byte $5b, $b8, $43, $47
	.byte $63, $34, $44, $3c
forest_inner_06_00:
	.byte $b4, $42, $26, $68
	.byte $d5, $23, $32, $22
	.byte $a8, $53, $33, $32
	.byte $aa, $85, $34, $42
	.byte $b8, $68, $82, $22
	.byte $68, $ad, $66, $99
	.byte $8b, $c8, $56, $97
	.byte $bb, $44, $65, $75
forest_inner_06_01:
	.byte $84, $22, $32, $95
	.byte $22, $46, $49, $b5
	.byte $33, $be, $32, $5c
	.byte $45, $cc, $66, $54
	.byte $29, $d9, $88, $33
	.byte $c9, $58, $86, $82
	.byte $9b, $b8, $8b, $62
	.byte $55, $bb, $83, $45
forest_inner_06_02:
	.byte $99, $db, $cb, $86
	.byte $55, $cb, $8b, $23
	.byte $b5, $23, $33, $66
	.byte $64, $b6, $86, $4b
	.byte $38, $6b, $68, $36
	.byte $34, $68, $48, $22
	.byte $8d, $22, $22, $36
	.byte $b9, $82, $33, $34
forest_inner_06_03:
	.byte $35, $de, $dd, $59
	.byte $68, $9b, $dd, $db
	.byte $69, $b9, $dd, $bb
	.byte $bd, $e9, $99, $69
	.byte $6d, $dd, $95, $56
	.byte $66, $6b, $cc, $bc
	.byte $b6, $55, $c8, $b6
	.byte $56, $b6, $43, $42
forest_inner_06_04:
	.byte $c9, $33, $8b, $66
	.byte $cb, $b2, $32, $23
	.byte $95, $66, $22, $32
	.byte $68, $bb, $82, $43
	.byte $5b, $c4, $62, $22
	.byte $bb, $44, $47, $77
	.byte $82, $36, $89, $77
	.byte $44, $36, $23, $99
forest_inner_06_05:
	.byte $22, $5c, $66, $bc
	.byte $23, $56, $69, $5c
	.byte $24, $36, $bc, $52
	.byte $62, $26, $46, $66
	.byte $26, $9d, $23, $86
	.byte $79, $b9, $52, $28
	.byte $96, $cb, $86, $22
	.byte $cb, $46, $8b, $43
forest_inner_06_06:
	.byte $cb, $b8, $88, $44
	.byte $8b, $c3, $43, $83
	.byte $33, $44, $34, $42
	.byte $44, $44, $84, $29
	.byte $b8, $86, $b6, $8d
	.byte $b6, $63, $38, $cc
	.byte $22, $42, $4b, $c9
	.byte $22, $25, $c5, $88
forest_inner_06_07:
	.byte $88, $86, $84, $4d
	.byte $24, $66, $25, $bc
	.byte $32, $22, $35, $85
	.byte $44, $34, $4b, $bb
	.byte $66, $52, $56, $88
	.byte $69, $97, $b8, $85
	.byte $87, $77, $8b, $ca
	.byte $66, $76, $58, $4c
forest_inner_07_00:
	.byte $54, $56, $53, $96
	.byte $86, $88, $85, $73
	.byte $8a, $65, $22, $79
	.byte $b5, $42, $32, $79
	.byte $d8, $33, $42, $66
	.byte $88, $44, $27, $75
	.byte $88, $87, $97, $8a
	.byte $86, $89, $96, $bd
forest_inner_07_01:
	.byte $88, $5d, $46, $46
	.byte $34, $cd, $c8, $bb
	.byte $2b, $bd, $d5, $66
	.byte $86, $66, $8c, $86
	.byte $bc, $d8, $8c, $a5
	.byte $6a, $bc, $b8, $84
	.byte $5a, $6c, $88, $5a
	.byte $85, $45, $68, $cc
forest_inner_07_02:
	.byte $db, $86, $43, $62
	.byte $46, $8b, $22, $25
	.byte $db, $84, $77, $75
	.byte $44, $44, $39, $97
	.byte $88, $66, $57, $b6
	.byte $33, $22, $27, $76
	.byte $63, $43, $77, $96
	.byte $84, $27, $77, $ad
forest_inner_07_03:
	.byte $58, $a8, $66, $43
	.byte $46, $dd, $c8, $b8
	.byte $3d, $de, $d8, $66
	.byte $7a, $5a, $ab, $42
	.byte $cc, $ea, $ac, $b5
	.byte $bb, $de, $c8, $65
	.byte $6b, $8d, $ba, $ac
	.byte $a8, $58, $b8, $cd
forest_inner_07_04:
	.byte $46, $b3, $34, $77
	.byte $68, $88, $62, $76
	.byte $64, $42, $27, $76
	.byte $82, $24, $32, $76
	.byte $23, $42, $22, $77
	.byte $44, $44, $27, $77
	.byte $a8, $22, $29, $97
	.byte $64, $22, $97, $99
forest_inner_07_05:
	.byte $55, $cb, $84, $43
	.byte $56, $44, $44, $22
	.byte $34, $88, $66, $5b
	.byte $22, $33, $22, $57
	.byte $23, $43, $43, $27
	.byte $92, $22, $24, $97
	.byte $7b, $77, $79, $6a
	.byte $79, $77, $97, $8c
forest_inner_07_06:
	.byte $33, $45, $6c, $58
	.byte $22, $55, $58, $bb
	.byte $77, $56, $83, $34
	.byte $79, $86, $3b, $86
	.byte $9c, $db, $22, $44
	.byte $cd, $dd, $63, $23
	.byte $88, $8c, $52, $44
	.byte $cb, $38, $a7, $97
forest_inner_07_07:
	.byte $8b, $66, $56, $55
	.byte $84, $65, $58, $85
	.byte $36, $66, $44, $58
	.byte $84, $54, $33, $35
	.byte $32, $79, $23, $4c
	.byte $32, $97, $22, $58
	.byte $25, $99, $75, $8b
	.byte $79, $77, $6b, $65
forest_inner_end:
